---
abstract: 'A plugin to MediaWiki::Bot providing admin functions'
author:
  - 'Dan Collins <en.wp.2t47@gmail.com>'
  - 'Mike.lifeguard <mike.lifeguard@gmail.com>'
  - 'patch and bug report contributors'
build_requires:
  File::Find: 0
  File::Temp: 0
  MediaWiki::Bot: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-Bot-Plugin-Admin
requires:
  Carp: 0
  Exporter: 0
  perl: 5.006
version: 3.2.1
