--- #YAML:1.0
name:                MediaWiki-Bot-Plugin-Admin
version:             0.1.0
abstract:            A plugin to MediaWiki::Bot providing admin functions
license:             gpl
author:              
    - Dan Collins (ST47)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    HTML::Entities:                1.35
    MediaWiki::Bot:                1.5.2
    URI::Escape:                   3.28
    WWW::Mechanize:                1.30
    XML::Simple:                   2.16
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
